# lang_config.py - Issac Terminal 深度智库词典 (v59.0)
LANG = {
    "CN": {
        "title": "🍎 Issac 机构级投研研究终端",
        "search_label": "🔍 个股透视 (回车搜索)",
        "sidebar_header": "⚙️ 专家级筛选参数",
        "pe_label": "最高 P/E (市盈率)",
        "pe_help": "P/E Ratio: 衡量回本年限。数值越低通常代表估值越便宜。科技股建议 < 35。",
        "peg_label": "最高 PEG (估值/增长比)",
        "peg_help": "PEG = P/E / 盈利增长率。机构公认：< 1.0 代表被低估，> 1.2 代表开始变贵。",
        "roe_label": "最低 ROE % (净资产收益率)",
        "roe_help": "ROE: 衡量公司赚钱效率。巴菲特最看重的指标，长期 > 15% 是绩优股门槛。",
        "fcf_label": "最低 FCF $B (自由现金流)",
        "fcf_help": "Free Cash Flow: 扣除开支后剩下的真金白银。现金流充沛的公司抗风险能力极强。",
        "snapshot_title": "📊 核心参数快照", 
        "report_title": "Issac 级深度投资研报 (Highly Confidential)",
        "chart_title": "📈 价格趋势与 MA200 支撑位",
        "chart_close": "收盘价", "chart_ma200": "200日线",
        "rs_title": "⚔️ 相对强度 (RS) 动能对比 (vs SPY)",
        "rs_help": "Relative Strength: 衡量该股跑赢标普 500 的能力。领头羊股在市场大跌时通常更抗跌。",
        "rs_label_spy": "标普 500 (SPY)",
        "rs_desc_leader": "🔥 **领头羊 (Leader)**：表现超越大盘 `{diff:.1f}%`。",
        "rs_desc_laggard": "🐌 **拖油瓶 (Laggard)**：表现落后大盘 `{diff:.1f}%`。",
        "earnings_radar_title": "🚦 财报胜率与盈利预测雷达",
        "next_earn_label": "📅 **预计下个财报日**",
        "prev_earn_label": "📊 **上季财报回顾 ({date})**",
        "eps_help": "EPS 惊喜度。实际值大幅超过预期通常是股价爆发的催化剂。",
        "moat_title": "🏰 维度一：商业模式与护城河透视",
        "industry": "细分行业", "summary": "业务简介",
        "moat_elite": "💎 **评级：顶级 (Elite)**。极高 ROE 意味着强大的定价权。",
        "moat_wide": "🛡️ **评级：宽阔 (Wide)**。拥有成熟壁垒，盈利质量高。",
        "moat_narrow": "🚧 **评级：较窄 (Narrow)**。面临激烈竞争。",
        "fin_title": "🏛️ 维度二：盈利质量、现金与债务审计",
        "consistency_label": "· **ROE 稳定性审计**: **{curr}%** (TTM) vs **{prev}%** (上年)。",
        "cash_label": "账面现金",
        "cash_help": "Total Cash: 账面总现金。高现金储备意味着强大的抗风险能力。",
        "debt_label": "总债务额",
        "debt_help": "Total Debt: 衡量财务压力。",
        "fcf_m_label": "FCF 利润率",
        "fcf_m_help": "FCF Margin: 自由现金流占营收比例。> 15% 是真正的‘印钞机’。",
        "debt_audit": "· **杠杆审计**: 负债权益比 **{val}%** — {status}",
        "pe_percentile_label": "· **估值水位**: 当前 P/E 处于过去一年 **{val}%** 分位。",
        "debt_healthy": "财务极其稳健", "debt_mid": "杠杆适中", "debt_high": "风险偏高",
        "risk_title": "🚩 维度三：筹码博弈、趋势与风险预警",
        "inst_label": "✅ **筹码分布**：机构持仓达 **{inst:.1f}%**。",
        "inst_help": "反映大资金信心。> 70% 代表该股是‘机构抱团股’。",
        "trend_bear": "❌ **趋势雷达**：股价处于 MA200 下方，多头动能瓦解。",
        "trend_bull": "📈 **趋势雷达**：股价站稳 MA200 上方，多头行情确立。",
        "stop_loss_label": "建议离场位 (基于 MA200 支撑)",
        "stop_loss_note": "注：该价位取 MA200 下方 3% 为缓冲区。若跌破建议离场。",
        "verdict_title": "🏆 Issac 级终极研判",
        "verdicts": ["避险 (C)","观望 (B)","建仓 (A)","重仓 (A+)"],
        "strategies": ["⚠️ 趋势极弱，等候信号。","⚖️ 缺乏动能，仅适合极轻仓。","✅ 趋势向好，逢低买入。","🔥 极品资产，量价齐飞！"],
        "strategy_label": "💡 策略指令",
        "score_label": "⭐ Issac 投研综合评分",
        "score_help": "基于基本面、技术面、大盘环境的量化评分。> 75 分代表高赢面。",
        "macro_title": "🌐 全球宏观风控雷达",
        "vix_label": "📉 恐慌指数 (VIX)",
        "vix_help": "VIX > 28 意味着极度恐慌；< 15 意味着市场非常平稳。",
        "tnx_label": "🏛️ 10年美债收益率",
        "tnx_help": "上升会压制科技股估值。它是全球资产定价之锚。",
        "mood_greed": "🟢 贪婪/平稳", "mood_fear": "🟡 谨慎/震荡", "mood_panic": "🔴 极度恐慌",
        "macro_alert": "🚨 **风控指令**：大环境恶劣，建议空仓回避！",
        "macro_explainer_title": "🧐 为什么当前处于：{mood}？",
        "macro_logic_panic": "🆘 **逻辑**：VIX 飙升且大盘跌破均线。全市场在踩踏。",
        "macro_logic_fear": "⚠️ **逻辑**：波动加大，资金避险。",
        "macro_logic_greed": "✅ **逻辑**：多头占优环境。",
        "macro_val_desc": "💡 分值越低代表市场越恐慌。0-25 是底部，75 以上是阶段性顶点。",
        "macro_hist_desc": "📜 历史上极度恐慌通常对应中长期底部。"
    },
    "EN": {
        "title": "🍎 Issac Investment Terminal",
        "search_label": "🔍 Manual Ticker Search",
        "sidebar_header": "⚙️ Expert Filters",
        "snapshot_title": "📊 Core Snapshot", 
        "report_title": "Institutional Deep Report",
        "verdict_title": "🏆 Verdict",
        "verdicts": ["Wait", "Hold", "Accumulate", "STRONG BUY"],
        "strategy_label": "💡 Strategy",
        "score_label": "⭐ Issac Score",
        "macro_title": "🌐 Macro Radar", "vix_label": "VIX", "tnx_label": "10Y Yield",
        "mood_greed": "🟢 Greed", "mood_fear": "🟡 Fear", "mood_panic": "🔴 Panic"
    }
}
