# lang_config.py - Issac Terminal 终极对齐版 (v55.0)
LANG = {
    "CN": {
        "title": "🍎 Issac 机构级投研研究终端",
        "search_label": "🔍 个股透视 (回车搜索)",
        "sidebar_header": "⚙️ 专家级筛选参数",
        "pe_label": "最高 P/E (市盈率)",
        "pe_help": "衡量估值。若公司亏损则显示 N/A。",
        "peg_label": "最高 PEG",
        "peg_help": "PEG < 1.0 代表估值低于增长速度。",
        "roe_label": "最低 ROE %",
        "roe_help": "巴菲特最看重的赚钱效率指标。",
        "fcf_label": "最低 FCF $B",
        "fcf_help": "自由现金流：公司手里的净现金。",
        "scan_range": "📊 批量扫描范围", "scan_btn": "开始批量扫描", "match_only": "🔍 只看符合条件的股票",
        "snapshot_title": "📊 核心参数快照", "report_title": "Issac 级深度投资研报 (Confidential)",
        "chart_title": "📈 股价与 200 日均线 (MA200) 趋势对比",
        "chart_close": "收盘价", "chart_ma200": "200日均线",
        "rs_title": "⚔️ 相对强度 (RS) 动能对比 (vs SPY)",
        "rs_help": "衡量个股跑赢大盘的能力。",
        "rs_label_spy": "标普 500 (SPY)",
        "rs_desc_leader": "🔥 **领头羊 (Leader)**：表现超越大盘 `{diff:.1f}%`。",
        "rs_desc_laggard": "🐌 **拖油瓶 (Laggard)**：表现落后大盘 `{diff:.1f}%`。",
        "earnings_radar_title": "🚦 财报胜率与盈利预测雷达",
        "next_earn_label": "📅 **下个财报日**: `{date}` (约 `{days}` 天后)",
        "prev_earn_label": "📊 **上季财报回顾 ({date})**",
        "eps_help": "EPS 惊喜度：实测值超过预期的比例。",
        "moat_title": "🏰 维度一：商业模式与护城河透视",
        "industry": "细分行业", "summary": "业务简介",
        "moat_elite": "💎 **顶级护城河**。ROE 极高，具垄断潜质。",
        "moat_wide": "🛡️ **宽阔护城河**。行业壁垒深厚。",
        "moat_narrow": "🚧 **护城河较窄**。面临激烈竞争。",
        "fin_title": "🏛️ 维度二：盈利质量、现金与债务审计",
        "cash_help": "账面总现金：反映公司的‘弹药库’。",
        "debt_help": "总负债：衡量杠杆压力。",
        "consistency_label": "· **ROE 稳定性审计**: **{curr}%** (TTM) vs **{prev}%** (上年)。",
        "cash_label": "· **现金储备**: **${val}B** (Total Cash)。",
        "debt_val_label": "· **债务总额**: **${val}B** (Total Debt)。",
        "debt_audit": "· **杠杆审计**: 负债权益比 **{val}%** — {status}",
        "pe_percentile_label": "· **估值水位**: 当前 P/E 处于过去一年 **{val}%** 分位。",
        "debt_healthy": "财务极其稳健", "debt_mid": "杠杆适中", "debt_high": "风险偏高",
        "risk_title": "🚩 维度三：筹码博弈、趋势与风险预警",
        "inst_label": "✅ **筹码分布**：机构持仓达 **{inst:.1f}%**。",
        "trend_bear": "❌ **趋势雷达**：股价处于 MA200 下方，多头瓦解。",
        "trend_bull": "📈 **趋势雷达**：股价站稳 MA200 上方，多头行情。",
        "stop_loss_label": "建议离场位 (基于 MA200 支撑)",
        "stop_loss_note": "注：建议在 MA200 下方 3% 设止损。",
        "verdict_title": "🏆 Issac 级终极研判",
        "verdicts": ["避险 (C)","观望 (B)","建仓 (A)","重仓 (A+)"],
        "strategies": ["⚠️ 趋势极弱。","⚖️ 缺乏动能。","✅ 趋势向好。","🔥 极品资产，持股！"],
        "strategy_label": "💡 策略指令",
        "score_label": "⭐ Issac 投研综合评分",
        "score_help": "量化评分。> 75 分代表高概率介入点。",
        "macro_title": "🌐 全球宏观风控雷达",
        "vix_label": "📉 恐慌指数 (VIX)",
        "tnx_label": "🏛️ 10年美债收益率",
        "mood_greed": "🟢 贪婪/平稳", "mood_fear": "🟡 谨慎/震荡", "mood_panic": "🔴 极度恐慌",
        "macro_alert": "🚨 **系统性风险警示**：当前大盘环境恶劣！",
        "macro_explainer_title": "🧐 为什么当前处于：{mood}？",
        "macro_logic_panic": "🆘 **逻辑**：VIX 飙升且大盘跌破均线。",
        "macro_logic_fear": "⚠️ **逻辑**：波动加大，资金避险。",
        "macro_logic_greed": "✅ **逻辑**：多头占优环境。",
        "macro_val_desc": "💡 0-25 是‘至暗时刻’，75 以上是‘狂欢终点’。",
        "macro_hist_desc": "📜 历史上极度恐慌通常对应中长期底部。"
    },
    "EN": {
        "title": "🍎 Issac Investment Terminal",
        "search_label": "🔍 Manual Ticker Search",
        "sidebar_header": "⚙️ Expert Filters",
        "pe_label": "Max P/E", "pe_help": "Price-to-Earnings Ratio.",
        "peg_label": "Max PEG", "peg_help": "P/E-to-Growth Ratio.",
        "roe_label": "Min ROE %", "roe_help": "Return on Equity.",
        "fcf_label": "Min FCF $B", "fcf_help": "Free Cash Flow.",
        "snapshot_title": "📊 Core Metrics Snapshot", "report_title": "Issac Deep Report",
        "chart_title": "📈 Price vs MA200",
        "chart_close": "Close", "chart_ma200": "MA200",
        "rs_title": "⚔️ Relative Strength (RS)",
        "rs_help": "Performance vs S&P 500.",
        "rs_label_spy": "S&P 500 (SPY)",
        "rs_desc_leader": "🔥 **Leader**: Outperformed SPY by `{diff:.1f}%`。",
        "rs_desc_laggard": "🐌 **Laggard**: Underperformed SPY by `{diff:.1f}%`。",
        "earnings_radar_title": "🚦 Earnings Radar",
        "next_earn_label": "📅 **Next Earnings**: `{date}` (In `{days}` days)",
        "prev_earn_label": "📊 **Last Earnings ({date})**",
        "eps_help": "Earnings surprise analytics.",
        "moat_title": "🏰 Pillar I: Moat Insight",
        "industry": "Industry", "summary": "Summary",
        "moat_elite": "💎 **Elite Moat**.",
        "moat_wide": "🛡️ **Wide Moat**.",
        "moat_narrow": "🚧 **Narrow Moat**.",
        "fin_title": "🏛️ Pillar II: Fundamentals",
        "consistency_label": "· **ROE Stability**: **{curr}%** (TTM) vs **{prev}%** (Ref).",
        "cash_label": "· **Cash**: **${val}B**.",
        "debt_val_label": "· **Total Debt**: **${val}B**.",
        "debt_audit": "· **Debt Audit**: D/E Ratio **{val}%** — {status}",
        "debt_help": "Debt-to-Equity Ratio.",
        "pe_percentile_label": "· **Valuation**: Current P/E is at **{val}%** percentile.",
        "debt_healthy": "Healthy", "debt_mid": "Moderate", "debt_high": "High Risk",
        "risk_title": "🚩 Pillar III: Risk Radar",
        "inst_help": "Ownership by institutions.",
        "trend_bear": "❌ **Bearish**: Below MA200。",
        "trend_bull": "📈 **Bullish**: Above MA200。",
        "stop_loss_label": "Exit Target",
        "stop_loss_note": "Buffer set at 3% below MA200.",
        "verdict_title": "🏆 Verdict",
        "verdicts": ["Wait", "Hold", "Accumulate", "STRONG CONVICTION"],
        "strategies": ["Wait.", "Monitor.", "Accumulate.", "Hold."],
        "strategy_label": "💡 Strategy",
        "score_label": "⭐ Composite Score",
        "score_help": "Quant score based on Quality and Momentum.",
        "macro_title": "🌐 Macro Radar", "vix_label": "📉 VIX", "vix_help": "Fear index.",
        "tnx_label": "🏛️ 10Y Yield", "tnx_help": "Asset pricing anchor.",
        "mood_greed": "🟢 Greed", "mood_fear": "🟡 Fear", "mood_panic": "🔴 Panic",
        "macro_explainer_title": "🧐 Why {mood}?",
        "macro_logic_panic": "🆘 Spike in VIX and breakdown.",
        "macro_logic_fear": "⚠️ Rising volatility.",
        "macro_logic_greed": "✅ Low VIX and uptrend.",
        "macro_val_desc": "💡 Lower = More Fear.",
        "macro_hist_desc": "📜 History shows low scores mark bottoms."
    }
}
